/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.st.server;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.eclipse.paho.client.mqttv3.MqttException;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it>
 */
public class ControlGUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControlGUIFrame
     */
    public ControlGUIFrame() {
        initComponents();
        this.jLabel_IP.setText(Utils.getIpAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_IP = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("STOP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("MQTT Status: ");

        jLabel_status.setText("status");

        jLabel2.setText("My IP: ");

        jLabel_IP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_IP.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_IP.setText("ipipip");

        jButton3.setText("youtube");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("SEND");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("POPULATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel_IP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(103, 103, 103)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_status))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_IP))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MQTT_Server_Manager.getInstance().connect();
        jLabel_status.setText("Online");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MQTT_Server_Manager.getInstance().disconnect();
        jLabel_status.setText("Offline");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Utils.openWebpage(new URI("https://www.youtube.com/watch?v=99n0yQG2pcI"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(ControlGUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String message = this.jTextField1.getText();
            MQTT_Server_Manager.getInstance().publish("speak", message);
            this.jTextField1.setText("");
            System.out.println("Message sent!");
        } catch (MqttException ex) {
            Logger.getLogger(ControlGUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    spamFakes();
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void spamFakes(){
        String m1 = "{\"name\":\"Mario\",\"surname\":\"Rossi\",\"gender\":\"MALE\",\"bornDate\":\"Sep 3, 2016 5:10:39 AM\",\"teleAssistent\":false,\"animation\":false,\"liveClose\":false,\"perceptionQuestionnary\":{\"Sezione V\":{\"a\":0,\"b\":4,\"c\":0,\"d\":0,\"e\":6,\"f\":0,\"g\":0,\"h\":0},\"Sezione III\":{\"a\":5,\"b\":4,\"c\":1,\"d\":0,\"e\":0,\"f\":0,\"g\":0,\"h\":0},\"Sezione VII\":{\"a\":0,\"b\":0,\"c\":7,\"d\":0,\"e\":0,\"f\":3,\"g\":0,\"h\":0},\"Sezione I\":{\"a\":5,\"b\":0,\"c\":5,\"d\":0,\"e\":0,\"f\":0,\"g\":0,\"h\":0},\"Sezione II\":{\"a\":0,\"b\":5,\"c\":0,\"d\":1,\"e\":2,\"f\":2},\"Sezione IV\":{\"a\":0,\"b\":0,\"c\":0,\"d\":0,\"e\":4,\"f\":3,\"g\":3,\"h\":0},\"Sezione VI\":{\"a\":0,\"b\":0,\"c\":0,\"d\":10,\"e\":0,\"f\":0,\"g\":0,\"h\":0}}}";
        String m2 = "{\"name\":\"Luca\",\"surname\":\"Coraci\",\"gender\":\"MALE\",\"bornDate\":\"Sep 2, 2016 11:56:54 PM\",\"teleAssistent\":true,\"animation\":false,\"liveClose\":false,\"perceptionQuestionnary\":{\"Sezione V\":{\"a\":0,\"b\":7,\"c\":3,\"d\":0,\"e\":0,\"f\":0,\"g\":0,\"h\":0},\"Sezione III\":{\"a\":1,\"b\":1,\"c\":2,\"d\":0,\"e\":3,\"f\":1,\"g\":2,\"h\":0},\"Sezione VII\":{\"a\":0,\"b\":3,\"c\":0,\"d\":4,\"e\":2,\"f\":0,\"g\":1,\"h\":0},\"Sezione I\":{\"a\":3,\"b\":7,\"c\":0,\"d\":0,\"e\":0,\"f\":0,\"g\":0,\"h\":0},\"Sezione II\":{\"a\":0,\"b\":1,\"c\":1,\"d\":2,\"e\":2,\"f\":4},\"Sezione IV\":{\"a\":0,\"b\":0,\"c\":0,\"d\":6,\"e\":3,\"f\":0,\"g\":1,\"h\":0},\"Sezione VI\":{\"a\":0,\"b\":0,\"c\":0,\"d\":0,\"e\":0,\"f\":0,\"g\":6,\"h\":4}}}";
        String m3 = "{\"name\":\"Isabella\",\"surname\":\"De Carli\",\"gender\":\"FEMALE\",\"bornDate\":\"Sep 6, 2008 5:10:39 AM\",\"teleAssistent\":false,\"animation\":false,\"liveClose\":true,\"perceptionQuestionnary\":{\"Sezione V\":{\"a\":0,\"b\":0,\"c\":1,\"d\":4,\"e\":0,\"f\":2,\"g\":2,\"h\":1},\"Sezione III\":{\"a\":0,\"b\":7,\"c\":0,\"d\":0,\"e\":0,\"f\":3,\"g\":0,\"h\":0},\"Sezione VII\":{\"a\":0,\"b\":0,\"c\":2,\"d\":2,\"e\":1,\"f\":3,\"g\":2,\"h\":0},\"Sezione I\":{\"a\":8,\"b\":0,\"c\":0,\"d\":0,\"e\":2,\"f\":0,\"g\":0,\"h\":0},\"Sezione II\":{\"a\":0,\"b\":1,\"c\":1,\"d\":0,\"e\":3,\"f\":5},\"Sezione IV\":{\"a\":0,\"b\":1,\"c\":1,\"d\":1,\"e\":1,\"f\":2,\"g\":4,\"h\":0},\"Sezione VI\":{\"a\":0,\"b\":0,\"c\":0,\"d\":1,\"e\":0,\"f\":9,\"g\":0,\"h\":0}}}";
        String m5 = "{\"name\":\"Carlo\",\"surname\":\"Bonifazi\",\"gender\":\"MALE\",\"bornDate\":\"Sep 9, 2016 4:01:49 AM\",\"teleAssistent\":false,\"animation\":false,\"liveClose\":false,\"perceptionQuestionnary\":{\"Sezione V\":{\"a\":0,\"b\":0,\"c\":0,\"d\":1,\"e\":8,\"f\":1,\"g\":0,\"h\":0},\"Sezione III\":{\"a\":0,\"b\":1,\"c\":6,\"d\":0,\"e\":3,\"f\":0,\"g\":0,\"h\":0},\"Sezione VII\":{\"a\":0,\"b\":0,\"c\":2,\"d\":2,\"e\":0,\"f\":1,\"g\":1,\"h\":4},\"Sezione I\":{\"a\":0,\"b\":1,\"c\":4,\"d\":4,\"e\":1,\"f\":0,\"g\":0,\"h\":0},\"Sezione II\":{\"a\":0,\"b\":3,\"c\":4,\"d\":0,\"e\":0,\"f\":3},\"Sezione IV\":{\"a\":0,\"b\":0,\"c\":0,\"d\":6,\"e\":0,\"f\":4,\"g\":0,\"h\":0},\"Sezione VI\":{\"a\":0,\"b\":0,\"c\":0,\"d\":0,\"e\":0,\"f\":10,\"g\":0,\"h\":0}}}";
        try {
            MQTT_Server_Manager.getInstance().publish("SUBSCRIPTION", m1);
            MQTT_Server_Manager.getInstance().publish("SUBSCRIPTION", m2);
            MQTT_Server_Manager.getInstance().publish("SUBSCRIPTION", m3);
            MQTT_Server_Manager.getInstance().publish("SUBSCRIPTION", m5);
        } catch (MqttException ex) {
            Logger.getLogger(ControlGUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlGUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_IP;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
