/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.sponsor.tt.gui.profiles.lr;

import it.cnr.istc.sponsor.tt.gui.profiles.mr.ProfileComboBoxModel;
import it.cnr.istc.sponsor.tt.gui.profiles.mr.ProfileComboBoxRenderer;
import it.cnr.istc.sponsor.tt.gui.profiles.mr.ProfileTableModel;
import it.cnr.istc.sponsor.tt.logic.model.Job;
import it.cnr.istc.sponsor.tt.logic.model.ModelManager;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it> ISTC-CNR
 */
public class LRJobSelectorPanel extends javax.swing.JPanel {

    private ProfileTableModel model = null;
    private String profileColumn0Label = "Ruoli";
    private ProfileComboBoxModel comboBoxModel;
    private ProfileComboBoxRenderer comboBoxRenderer;

    /**
     * Creates new form LRJobSelectorPanel
     */
    public LRJobSelectorPanel() {
        initComponents();
        this.jPanel_Advanced.setVisible(false);

        String[] skillNames = ModelManager.getInstance().getAllSkills().stream().map(skill -> skill.getName()).toArray(String[]::new);
        String[] columns = new String[skillNames.length + 1];
        columns[0] = profileColumn0Label;
        for (int i = 0; i < skillNames.length; i++) {
            columns[i + 1] = skillNames[i];
        }
        model = new ProfileTableModel(columns);
        this.jTable1.setModel(model);
        jTable1.setRowHeight(32);
        jTable1.setSelectionBackground(new java.awt.Color(102, 255, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 204));
        ((JComponent) jTable1.getDefaultRenderer(Boolean.class)).setOpaque(true);

        List<Job> profiles = ModelManager.getInstance().getProfiles();
        profiles.add(0, new Job(" + Nuovo Profilo"));
//        
        comboBoxModel = new ProfileComboBoxModel(profiles);
        this.jComboBox_profiles.setModel(comboBoxModel);
        this.jComboBox_profiles.setSelectedIndex(0);
//        this.jComboBox_profiles.setRenderer(comboBoxRenderer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel_Data = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel_date = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jButton1 = new JButton();
        jPanel_Advanced = new JPanel();
        jPanel2 = new JPanel();
        jCheckBox_skill9 = new JCheckBox();
        jCheckBox_skill10 = new JCheckBox();
        jCheckBox_skill11 = new JCheckBox();
        jCheckBox_skill12 = new JCheckBox();
        jCheckBox_skill13 = new JCheckBox();
        jCheckBox_skill14 = new JCheckBox();
        jCheckBox_skill15 = new JCheckBox();
        jLabel5 = new JLabel();
        jSpinner1 = new JSpinner();
        jLabel6 = new JLabel();
        jCheckBox_Advanced = new JCheckBox();
        jComboBox_profiles = new JComboBox<>();

        jLabel1.setText("Turno del:");

        jLabel_Data.setText("17:00");

        jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2.setText("dalle:");

        jLabel3.setText("16:00");

        jLabel4.setText("alle");

        jLabel_date.setText("jLabel5");

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Inserisci");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel_Advanced.setBackground(new Color(204, 255, 204));

        jPanel2.setBorder(BorderFactory.createTitledBorder("Seleziona i giorni della settimana dove vuoi ripetere questo turno"));

        jCheckBox_skill9.setBackground(new Color(255, 255, 255));
        jCheckBox_skill9.setText("Lunedì");
        jCheckBox_skill9.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill9.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill9.setVerticalTextPosition(SwingConstants.TOP);

        jCheckBox_skill10.setBackground(new Color(255, 255, 255));
        jCheckBox_skill10.setText("Martedì");
        jCheckBox_skill10.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill10.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill10.setVerticalTextPosition(SwingConstants.TOP);

        jCheckBox_skill11.setBackground(new Color(255, 255, 255));
        jCheckBox_skill11.setText("Mercoledì");
        jCheckBox_skill11.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill11.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill11.setVerticalTextPosition(SwingConstants.TOP);

        jCheckBox_skill12.setBackground(new Color(255, 255, 255));
        jCheckBox_skill12.setText("Giovedì");
        jCheckBox_skill12.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill12.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill12.setVerticalTextPosition(SwingConstants.TOP);

        jCheckBox_skill13.setBackground(new Color(255, 255, 255));
        jCheckBox_skill13.setText("Venerdì");
        jCheckBox_skill13.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill13.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill13.setVerticalTextPosition(SwingConstants.TOP);

        jCheckBox_skill14.setBackground(new Color(255, 255, 255));
        jCheckBox_skill14.setText("Sabato");
        jCheckBox_skill14.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill14.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill14.setVerticalTextPosition(SwingConstants.TOP);

        jCheckBox_skill15.setBackground(new Color(255, 255, 255));
        jCheckBox_skill15.setText("Domenica");
        jCheckBox_skill15.setHorizontalAlignment(SwingConstants.CENTER);
        jCheckBox_skill15.setHorizontalTextPosition(SwingConstants.CENTER);
        jCheckBox_skill15.setVerticalTextPosition(SwingConstants.TOP);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_skill9, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_skill10, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_skill11, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_skill12, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_skill13, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_skill14, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_skill15, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_skill15)
                    .addComponent(jCheckBox_skill14)
                    .addComponent(jCheckBox_skill13)
                    .addComponent(jCheckBox_skill12)
                    .addComponent(jCheckBox_skill11)
                    .addComponent(jCheckBox_skill10)
                    .addComponent(jCheckBox_skill9))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("ripeti questa modello per: ");

        jLabel6.setText("settimane");

        GroupLayout jPanel_AdvancedLayout = new GroupLayout(jPanel_Advanced);
        jPanel_Advanced.setLayout(jPanel_AdvancedLayout);
        jPanel_AdvancedLayout.setHorizontalGroup(jPanel_AdvancedLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel_AdvancedLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_AdvancedLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AdvancedLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel_AdvancedLayout.setVerticalGroup(jPanel_AdvancedLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdvancedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AdvancedLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox_Advanced.setText("Avanzate");
        jCheckBox_Advanced.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox_AdvancedActionPerformed(evt);
            }
        });

        jComboBox_profiles.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_profiles.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jComboBox_profilesActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_date, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Data, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_profiles, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox_Advanced)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_Advanced, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Data)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_date)
                    .addComponent(jComboBox_profiles, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Advanced, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox_Advanced)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_profilesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox_profilesActionPerformed
        
    }//GEN-LAST:event_jComboBox_profilesActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox_profiles.getSelectedIndex() != 0) {
            this.model.addRowElement((Job) jComboBox_profiles.getSelectedItem());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox_AdvancedActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox_AdvancedActionPerformed
        this.jPanel_Advanced.setVisible(this.jCheckBox_Advanced.isSelected());
    }//GEN-LAST:event_jCheckBox_AdvancedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JCheckBox jCheckBox_Advanced;
    private JCheckBox jCheckBox_skill10;
    private JCheckBox jCheckBox_skill11;
    private JCheckBox jCheckBox_skill12;
    private JCheckBox jCheckBox_skill13;
    private JCheckBox jCheckBox_skill14;
    private JCheckBox jCheckBox_skill15;
    private JCheckBox jCheckBox_skill9;
    private JComboBox<String> jComboBox_profiles;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel_Data;
    private JLabel jLabel_date;
    private JPanel jPanel2;
    private JPanel jPanel_Advanced;
    private JScrollPane jScrollPane1;
    private JSpinner jSpinner1;
    private JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
