/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.sponsor.tt.gui.profiles;

import it.cnr.istc.sponsor.tt.gui.people.PeopleKeywordDialog;
import it.cnr.istc.sponsor.tt.logic.model.Keyword;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it> ISTC-CNR
 */
public class MiniSingleKeyPanel extends javax.swing.JPanel {

    private ImageIcon iconAdd = new ImageIcon(getClass().getResource("/it/cnr/istc/sponsor/tt/gui/icons/add16.png"));
    private ImageIcon iconAvoid = new ImageIcon(getClass().getResource("/it/cnr/istc/sponsor/tt/gui/icons/avoid16.png"));
    private Keyword keyword = null;
    private boolean avoid = false;
//    private PeopleKeywordDialog parent = null; 
    private Component parent = null; 
    
    /**
     * Creates new form MiniSingleKeyPanel
     */
    public MiniSingleKeyPanel(boolean avoid, Keyword key) {
        initComponents();
        this.keyword = key;
        this.avoid = avoid;
        this.jLabel_icon.setIcon(avoid ? iconAvoid : iconAdd);
        this.jLabel2.setText(key.getKeyword());
        this.setBackground(Color.WHITE);
    }

    public void setParent(Component parent) {
        this.parent = parent;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_icon = new JLabel();
        jLabel2 = new JLabel();
        jButton1 = new JButton();

        setBackground(new Color(255, 255, 255));

        jLabel2.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 204));
        jLabel2.setText("jLabel2");

        jButton1.setIcon(new ImageIcon(getClass().getResource("/it/cnr/istc/sponsor/tt/gui/icons/delete16_1.png"))); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_icon, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_icon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //REMOVE ME
        if(this.parent != null && this.parent instanceof PeopleKeywordDialog){
            ((PeopleKeywordDialog)this.parent).removeKeyword(this.keyword.getKeyword());
        }
        if(this.parent != null && this.parent instanceof SingleKeywordPanel){
            ((SingleKeywordPanel)this.parent).removeKeyword(this.keyword.getKeyword());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public Keyword getKeyword() {
        return keyword;
    }

    public boolean isAvoid() {
        return avoid;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        Dimension arcs = new Dimension(15,15); //Border corners arcs {width,height}, change this to whatever you want
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);


        //Draws the rounded panel with borders.
        graphics.setColor(avoid ? new Color(100,0,0) : new Color(0,120,0));
        graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint background
        graphics.setColor(getForeground());
        graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint border
//        setBackground(Color.WHITE);
    }

    
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JLabel jLabel2;
    private JLabel jLabel_icon;
    // End of variables declaration//GEN-END:variables
}
